services:
  besu:
    image: hyperledger/besu:latest
    container_name: besu-node
    command: >
      --network=dev
      --miner-enabled
      --miner-coinbase=0x0000000000000000000000000000000000000000
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --host-allowlist=*
      --rpc-http-api=ETH,NET,WEB3,TXPOOL
      --rpc-http-cors-origins=all
      --data-path=/var/lib/besu/data
      --min-gas-price=0
    ports:
      - "8545:8545"
    volumes:
      - ./besu-data:/var/lib/besu/data
